=== ft-seilbahn-projekt/modellsteuerung-backend/configurator/config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "names": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "maxled": {
      "type": "integer"
    },
    "type": {
      "type": "string"
    },
    "io": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "value"
          ]
        }
      ]
    }
  },
  "required": [
    "names",
    "maxled",
    "type",
    "io"
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/testbench/uselessguy.json
{
  "names": [
    "ftSwarm3"
  ],
  "maxled": 2,
  "type": "xl",
  "io": [
    {
      "id": "hostname",
      "value": "uselessguy"
    },
    {
      "id": "A8",
      "value": "deskspdp"
    },
    {
      "id": "A7",
        "value": "emergi"
    },
    {
      "id": "A6",
      "value": "cablelocout"
    },
    {
      "id": "A5",
      "value": "spcclampclosed"
    },
    {
      "id": "A4",
      "value": "spcwfrend"
    },
    {
      "id": "A3",
      "value": "spcwbend"
    },
    {
      "id": "A2",
      "value": "spcwbwrn"
    },
    {
      "id": "A1",
      "value": "spcclamp"
    }
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/spinellivorne.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm109"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "spivorne"
        },
        {
            "id": "A1",
            "value": "spfntc"
        },
        {
            "id": "A2",
            "value": "spcclamp"
        },
        {
            "id": "A3",
            "value": "spcwbwrn"
        },
        {
            "id": "A4",
            "value": "spcwbend"
        },
        {
            "id": "A5",
            "value": "spcwfwrn"
        },
        {
            "id": "A6",
            "value": "spcwfrend"
        },
        {
            "id": "M1",
            "value": "ospftrack"
        },
        {
            "id": "M2",
            "value": "ospftransport"
        }
    ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/mast2.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm108"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "mast2"
        },
        {
            "id": "A1",
            "value": "m2ntc"
        },
        {
            "id": "M2",
            "value": "om2top"
        }
    ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/testbench/kelda.json
{
  "names": [
    "ftSwarm2"
  ],
  "maxled": 2,
  "type": "xl",
  "io": [
    {
      "id": "hostname",
      "value": "kelda"
    },
    {
      "id": "A8",
      "value": "deskspd1"
    },
    {
      "id": "A7",
      "value": "deskspd2"
    },
    {
      "id": "A6",
      "value": "deskspd3"
    },
    {
      "id": "A5",
      "value": "lubntc"
    },
    {
      "id": "A4",
      "value": "lufkey"
    },
    {
      "id": "A3",
      "value": "lubemerg"
    },
    {
      "id": "A2",
      "value": "lucclampclosed"
    },
    {
      "id": "A1",
      "value": "spbntc"
    }
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/desk2.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm101"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "desk2"
        },
        {
            "id": "A1",
            "value": "deskspdp"
        },
        {
            "id": "A2",
            "value": "deskqb"
        },
        {
            "id": "A3",
            "value": "deskqs"
        },
        {
            "id": "A4",
            "value": "deskgo"
        },
        {
            "id": "A5",
            "value": "desksig"
        },
        {
            "id": "A6",
            "value": "deskcis"
        },
        {
            "id": "M1",
            "value": "odeskgo"
        },
        {
            "id": "M2",
            "value": "odeskon"
        }
    ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/luisevorn.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm12"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "luisevorn"
        },
        {
            "id": "A1",
            "value": "lufntc"
        },
        {
            "id": "A2",
            "value": "spcclamp"
        },
        {
            "id": "A3",
            "value": "spcclampclosed"
        },
        {
            "id": "A6",
            "value": "lufkey"
        },
        {
            "id": "M1",
            "value": "oluftransport"
        },
        {
            "id": "M2",
            "value": "oluftrack"
        }
    ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/desk1.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm100"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "desk1"
        },
        {
            "id": "A1",
            "value": "deskwrn"
        },
        {
            "id": "A2",
            "value": "deskemerg"
        },
        {
            "id": "A3",
            "value": "deskemergsb"
        },
        {
            "id": "A4",
            "value": "deskspd1"
        },
        {
            "id": "A5",
            "value": "deskspd2"
        },
        {
            "id": "A6",
            "value": "deskspd3"
        },
        {
            "id": "M1",
            "value": "odeskcnfop"
        },
        {
            "id": "M2",
            "value": "odeskcnfsys"
        }
    ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/desk3.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm113"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "desk3"
        },
        {
            "id": "A1",
            "value": "deskkom1"
        },
        {
            "id": "A2",
            "value": "deskkom2"
        },
        {
            "id": "A3",
            "value": "deskon"
        },
        {
            "id": "A4",
            "value": "desksta"
        },
        {
            "id": "A5",
            "value": "deskfg"
        },
        {
            "id": "A6",
            "value": "deskser"
        },
        {
            "id": "M1",
            "value": "odesksta"
        },
        {
            "id": "M2",
            "value": "odeskfd"
        }
    ]
}
