=== ft-seilbahn-projekt/modellsteuerung-backend/configurator/config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "names": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "maxled": {
      "type": "integer"
    },
    "type": {
      "type": "string"
    },
    "io": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "value"
          ]
        }
      ]
    }
  },
  "required": [
    "names",
    "maxled",
    "type",
    "io"
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/testbench/errgehbeh.json
{
  "names": [
    "ftSwarm102"
  ],
  "maxled": 18,
  "type": "rs",
  "io": [
    {
      "id": "A1",
      "value": "lufntc"
    },
    {
      "id": "LED3",
      "value": "okey"
    },
    {
      "id": "LED4",
      "value": "ofirel"
    },
    {
      "id": "LED5",
      "value": "ounknown2l"
    },
    {
      "id": "LED6",
      "value": "ounknown3l"
    },
    {
      "id": "LED7",
      "value": "ocablelocout"
    },
    {
      "id": "LED8",
      "value": "ofirer"
    },
    {
      "id": "LED9",
      "value": "ounknown2r"
    },
    {
      "id": "LED10",
      "value": "ounknown3r"
    },
    {
      "id": "LED11",
      "value": "ocablelocin"
    },
    {
      "id": "LED12",
      "value": "osimf"
    },
    {
      "id": "LED13",
      "value": "osimb"
    },
    {
      "id": "LED14",
      "value": "osimfl"
    },
    {
      "id": "LED15",
      "value": "osimn"
    },
    {
      "id": "LED16",
      "value": "osimfa"
    },
    {
      "id": "LED17",
      "value": "osimmnot"
    },
    {
      "id": "LED18",
      "value": "osimlock"
    }
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/testbench/dip_right.json
{
  "names": [
    "ftSwarm180"
  ],
  "maxled": 2,
  "type": "xl",
  "io": [
    {
      "id": "hostname",
      "value": "dipright"
    },
    {
      "id": "A8",
      "value": "deskemergsb"
    },
    {
      "id": "A7",
      "value": "deskemerg"
    },
    {
      "id": "A6",
      "value": "deskwrn"
    },
    {
      "id": "A5",
      "value": "deskcis"
    },
    {
      "id": "A4",
      "value": "deskgo"
    },
    {
      "id": "A3",
      "value": "deskqs"
    },
    {
      "id": "A2",
      "value": "deskqb"
    },
    {
      "id": "A1",
      "value": "deskser"
    },
    {
      "id": "M1",
      "value": "oemergproblem"
    },
    {
      "id": "M2",
      "value": "oemergresolve"
    },
    {
      "id": "M3",
      "value": "om1top"
    },
    {
      "id": "M4",
      "value": "om2top"
    },
    {
      "id": "M5",
      "value": "om3top"
    },
    {
      "id": "M6",
      "value": "om3flight"
    }
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/luisehinten.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm13"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "luisehnd"
        },
        {
            "id": "A1",
            "value": "lubntc"
        },
        {
            "id": "A6",
            "value": "lubemerg"
        },
        {
            "id": "M1",
            "value": "olubtransport"
        },
        {
            "id": "M2",
            "value": "olubtrack"
        }
    ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/notausampel.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm7"
    ],
    "type": "rs",
    "maxled": 10,
    "io": [
        {
            "id": "hostname",
            "value": "naampel"
        },
        {
            "id": "A1",
            "value": "cablelocout"
        },
        {
            "id": "A2",
            "value": "cablelocin"
        },
        {
            "id": "M1",
            "value": "ospbtrack"
        },
        {
            "id": "M2",
            "value": "ospbtransport"
        },
        {
            "id": "LED3",
            "value": "ofirer"
        },
        {
            "id": "LED4",
            "value": "ouoner"
        },
        {
            "id": "LED5",
            "value": "outwor"
        },
        {
            "id": "LED6",
            "value": "ofirel"
        },
        {
            "id": "LED7",
            "value": "ouonel"
        },
        {
            "id": "LED8",
            "value": "outwol"
        },
        {
            "id": "LED9",
            "value": "ocablelocout"
        },
        {
            "id": "LED10",
            "value": "ocablelocin"
        }
    ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/desk4.json
{
  "$schema": "../../configurator/config_schema.json",
  "names": ["ftSwarm112"],
  "type": "rs",
  "maxled": 3,
  "io": [
    {
      "id": "hostname",
      "value": "desk4"
    },
    {
      "id": "A1",
      "value": "deskvw"
    },
    {
      "id": "A2",
      "value": "deskrw"
    },
    {
      "id": "A3",
      "value": "deskcall"
    },
    {
      "id": "A6",
      "value": "deskkey"
    },
    {
      "id": "M1",
      "value": "odeskserv"
    },
    {
      "id": "M2",
      "value": "odeskdir"
    },
    {
      "id": "LED3",
      "value": "okey"
    }
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/testbench/dip_left.json
{
  "names": [
    "ftSwarm1"
  ],
  "maxled": 2,
  "type": "xl",
  "io": [
    {
      "id": "hostname",
      "value": "dipleft"
    },
    {
      "id": "A8",
      "value": "deskfg"
    },
    {
      "id": "A7",
      "value": "desksta"
    },
    {
      "id": "A6",
      "value": "deskon"
    },
    {
      "id": "A5",
      "value": "deskcall"
    },
    {
      "id": "A4",
      "value": "deskrw"
    },
    {
      "id": "A3",
      "value": "deskvw"
    },
    {
      "id": "A2",
      "value": "cablelocin"
    },
    {
      "id": "A1",
      "value": "spcwfrwrn"
    },
    {
      "id": "M1",
      "value": "odeskcnfsys"
    },
    {
      "id": "M2",
      "value": "odeskcnfop"
    },
    {
      "id": "M3",
      "value": "odeskgo"
    },
    {
      "id": "M4",
      "value": "odeskon"
    },
    {
      "id": "M5",
      "value": "odeskfd"
    },
    {
      "id": "M6",
      "value": "odesksta"
    },
    {
      "id": "M7",
      "value": "odeskdir"
    },
    {
      "id": "M8",
      "value": "odeskserv"
    }
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/testbench/next_to_power.json
{
  "names": [
    "ftSwarm4"
  ],
  "maxled": 2,
  "type": "xl",
  "io": [
    {
      "id": "hostname",
      "value": "nexttopower"
    },
    {
      "id": "A8",
      "value": "deskkom1"
    },
    {
      "id": "A7",
      "value": "deskkom2"
    },
    {
      "id": "A6",
      "value": "deskkey"
    },
    {
      "id": "A5",
      "value": "spfntc"
    },
    {
      "id": "A4",
      "value": "m1ntc"
    },
    {
      "id": "A3",
      "value": "m2ntc"
    },
    {
      "id": "A2",
      "value": "m3ntc"
    },
    {
      "id": "A1",
      "value": "lucclamp"
    }
  ]
}

=== ft-seilbahn-projekt/modellsteuerung-backend/configurations/live/notaus.json
{
    "$schema": "../../configurator/config_schema.json",
    "names": [
        "ftSwarm5"
    ],
    "type": "rs",
    "maxled": 2,
    "io": [
        {
            "id": "hostname",
            "value": "notaus"
        },
        {
            "id": "A1",
            "value": "emergi"
        },
        {
            "id": "A6",
            "value": "spbntc"
        },
        {
            "id": "M1",
            "value": "oemergresolve"
        },
        {
            "id": "M2",
            "value": "oemergproblem"
        }
    ]
}
